# Generated by Django 6.0.7 on 2026-07-23 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد رایانه بیمه نامه')),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره بیمه نامه')),
                ('policyholder', models.CharField(max_length=255, verbose_name='بیمه گذار')),
                ('contract_number', models.TextField(blank=True, null=True, verbose_name='شماره قرارداد')),
                ('contract_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='شرح قرارداد')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت')),
                ('start_date', models.CharField(blank=True, help_text='فرمت: 1405/04/29', max_length=20, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.CharField(blank=True, help_text='فرمت: 1405/04/29', max_length=20, null=True, verbose_name='تاریخ انقضاء')),
                ('issue_date', models.CharField(blank=True, help_text='فرمت: 1405/04/29', max_length=20, null=True, verbose_name='تاریخ صدور')),
                ('duration_days', models.IntegerField(blank=True, null=True, verbose_name='مدت (روز)')),
                ('total_premium', models.BigIntegerField(blank=True, null=True, verbose_name='کل حق بیمه (ریال)')),
                ('vat', models.BigIntegerField(blank=True, null=True, verbose_name='مالیات ارزش افزوده')),
                ('total_with_tax', models.BigIntegerField(blank=True, null=True, verbose_name='حق بیمه با مالیات و عوارض (ریال)')),
                ('plate_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پلاک')),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع وسیله نقلیه')),
                ('vehicle_year', models.IntegerField(blank=True, null=True, verbose_name='سال ساخت')),
                ('body_coverage', models.BigIntegerField(blank=True, null=True, verbose_name='پوشش بدنی (میلیون ریال)')),
                ('financial_coverage', models.BigIntegerField(blank=True, null=True, verbose_name='پوشش مالی (میلیون ریال)')),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف / نماینده')),
                ('archive_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره بایگانی')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='داده خام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'بیمه نامه',
                'verbose_name_plural': 'بیمه نامه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(verbose_name='شماره قسط')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ قسط (ریال)')),
                ('due_date', models.CharField(help_text='فرمت: 1405/04/29', max_length=20, verbose_name='تاریخ سررسید')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('overdue', 'دیرکرد'), ('partial', 'پرداخت جزیی')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='policies.insurancepolicy', verbose_name='بیمه نامه')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'اقساط',
                'ordering': ['policy', 'installment_number'],
                'unique_together': {('policy', 'installment_number')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ واریزی (ریال)')),
                ('payment_date', models.CharField(help_text='فرمت: 1405/04/29', max_length=20, verbose_name='تاریخ واریز')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت به کارت'), ('check', 'چک'), ('wire', 'حواله بانکی'), ('other', 'سایر')], default='cash', max_length=20, verbose_name='روش پرداخت')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پیگیری')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='policies.installment', verbose_name='قسط')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='policies.insurancepolicy', verbose_name='بیمه نامه')),
            ],
            options={
                'verbose_name': 'واریزی',
                'verbose_name_plural': 'واریزی\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
