# Generated by Django 6.0.7 on 2026-07-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='نشانی'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='national_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='phone',
            field=models.CharField(blank=True, help_text='مثال: 09121234567', max_length=50, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='شماره پیگیری یکتا - نمی\u200cتواند تکراری باشد', max_length=100, null=True, unique=True, verbose_name='شماره پیگیری'),
        ),
    ]
