# Generated by Django 6.0.7 on 2026-07-23 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_insurancepolicy_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع بیمه')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='شناسه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'نوع بیمه',
                'verbose_name_plural': 'انواع بیمه',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='vehicle_value',
            field=models.BigIntegerField(blank=True, help_text='مخصوص بیمه بدنه', null=True, verbose_name='ارزش وسیله نقلیه (ریال)'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='insurance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='policies.insurancetype', verbose_name='نوع بیمه'),
        ),
    ]
