# Generated by Django 6.0.7 on 2026-07-23 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_insurancetype_insurancepolicy_vehicle_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='down_payment',
            field=models.BigIntegerField(blank=True, default=0, help_text='مبلغ پیش پرداخت که از کل کسر و باقی\u200cمانده قسط\u200cبندی می\u200cشود', null=True, verbose_name='پیش پرداخت (ریال)'),
        ),
        migrations.CreateModel(
            name='GuaranteeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.CharField(max_length=100, verbose_name='شماره چک')),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام بانک')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ چک (ریال)')),
                ('due_date', models.CharField(help_text='فرمت: 1405/04/29', max_length=20, verbose_name='تاریخ سررسید')),
                ('status', models.CharField(choices=[('pending', 'در انتظار وصول'), ('cleared', 'وصول شده'), ('returned', 'برگشت خورده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_checks', to='policies.insurancepolicy', verbose_name='بیمه نامه')),
            ],
            options={
                'verbose_name': 'چک ضمانت',
                'verbose_name_plural': 'چک\u200cهای ضمانت',
                'ordering': ['-created_at'],
            },
        ),
    ]
