# Generated by Django 6.0.7 on 2026-07-25 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_insurancepolicy_down_payment_guaranteecheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ الحاقیه (ریال)')),
                ('reason', models.CharField(default='تغییر دیه', help_text='مثال: تغییر دیه سال ۱۴۰۵', max_length=500, verbose_name='دلیل الحاقیه')),
                ('date', models.CharField(help_text='فرمت: 1405/04/29', max_length=20, verbose_name='تاریخ ثبت')),
                ('previous_total', models.BigIntegerField(verbose_name='مبلغ کل قبل از الحاقیه')),
                ('new_total', models.BigIntegerField(verbose_name='مبلغ کل بعد از الحاقیه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='policies.insurancepolicy', verbose_name='بیمه نامه')),
            ],
            options={
                'verbose_name': 'الحاقیه',
                'verbose_name_plural': 'الحاقیه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
