# Generated by Django 6.0.7 on 2026-07-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_add_endorsement'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='down_payment_date',
            field=models.CharField(blank=True, help_text='فرمت: 1405/04/29', max_length=20, null=True, verbose_name='تاریخ پرداخت پیش پرداخت'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='down_payment_paid',
            field=models.BooleanField(default=False, verbose_name='پیش پرداخت پرداخت شد؟'),
        ),
    ]
