# Generated by Django 6.0.7 on 2026-07-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_insurancepolicy_down_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='overpayment_credit',
            field=models.BigIntegerField(blank=True, default=0, help_text='اضافه پرداختی که به قسط بعدی اعمال می\u200cشود', null=True, verbose_name='اعتبار اضافه پرداخت (ریال)'),
        ),
    ]
