# Generated by Django 6.0.7 on 2026-07-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_overpayment_credit_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='check_bank_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام بانک'),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_due_date',
            field=models.CharField(blank=True, help_text='فرمت: 1405/04/29', max_length=20, null=True, verbose_name='تاریخ سررسید چک'),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار وصول'), ('cleared', 'پاس شده'), ('returned', 'برگشت خورده')], default=None, help_text='وضعیت وصول چک', max_length=20, null=True, verbose_name='وضعیت چک'),
        ),
    ]
