# Generated by Django 6.0.7 on 2026-07-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0008_cheque_payment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت به کارت'), ('check', 'چک'), ('wire', 'حواله بانکی'), ('credit', 'پرداخت از اعتبار'), ('other', 'سایر')], default='cash', max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
