# Generated by Django 6.0.7 on 2026-07-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0009_credit_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='agent_phone',
            field=models.CharField(blank=True, help_text='مثال: 09121234567', max_length=50, null=True, verbose_name='شماره تماس معرف'),
        ),
    ]
