# Generated by Django 6.0.7 on 2026-07-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0010_agent_phone_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='introducer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف / ضامن'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='introducer_phone',
            field=models.CharField(blank=True, help_text='مثال: 09121234567', max_length=50, null=True, verbose_name='شماره تماس معرف'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نماینده فروش'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='agent_phone',
            field=models.CharField(blank=True, help_text='مثال: 09121234567', max_length=50, null=True, verbose_name='شماره تماس نماینده'),
        ),
    ]
