# Generated by Django 6.0.7 on 2026-07-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0011_introducer_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید')),
                ('label', models.CharField(max_length=200, verbose_name='عنوان')),
                ('value', models.BooleanField(default=True, verbose_name='فعال')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
                'ordering': ['category', 'key'],
            },
        ),
    ]
