# Generated by Django 6.0.7 on 2026-07-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0012_app_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='commission_amount',
            field=models.BigIntegerField(blank=True, default=None, help_text='به صورت خودکار محاسبه می\u200cشود', null=True, verbose_name='مبلغ کمیسیون (ریال)'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='مثال: 10 = 10%', max_digits=5, null=True, verbose_name='درصد کمیسیون'),
        ),
    ]
