# Generated by Django 6.0.7 on 2026-07-26 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0013_commission_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuredPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('national_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تماس')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insured_persons', to='policies.insurancepolicy', verbose_name='بیمه نامه')),
            ],
            options={
                'verbose_name': 'فرد تحت پوشش',
                'verbose_name_plural': 'افراد تحت پوشش',
                'ordering': ['full_name'],
            },
        ),
    ]
