# Generated by Django 6.0.7 on 2026-07-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0014_insured_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsuredPerson',
        ),
    ]
