# Generated by Django 6.0.7 on 2026-07-26 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0015_remove_insured_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام بانک')),
                ('account_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره حساب')),
                ('card_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره کارت')),
                ('sheba', models.CharField(blank=True, max_length=30, null=True, verbose_name='شبا')),
                ('balance', models.BigIntegerField(default=0, verbose_name='موجودی (ریال)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته')),
                ('color', models.CharField(default='#6c757d', help_text='کد رنگ هگز', max_length=20, verbose_name='رنگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته هزینه',
                'verbose_name_plural': 'دسته\u200cبندی هزینه\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت')], max_length=20, verbose_name='نوع')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ (ریال)')),
                ('date', models.CharField(help_text='فرمت: 1405/04/29', max_length=20, verbose_name='تاریخ')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='شرح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='policies.bankaccount', verbose_name='حساب')),
            ],
            options={
                'verbose_name': 'تراکنش بانکی',
                'verbose_name_plural': 'تراکنش\u200cهای بانکی',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ (ریال)')),
                ('date', models.CharField(help_text='فرمت: 1405/04/29', max_length=20, verbose_name='تاریخ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.expensecategory', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'هزینه',
                'verbose_name_plural': 'هزینه\u200cها',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
